### ISSUE TITLE
[Question] Few questions

### ISSUE THREAD

**Issue by Bia10** [JeremyKuhne/thirtytwo#1]
Hello,

First and foremost thank you very much for this, its exactly what I have been missing from Win32InterOps. There are quite a few things I am not entirely certain how to proceed in using this project, so I hope you don't mind id ask for your opinion.

## OnLoad event

WinForms have useful event OnLoad, how do I "replicate" this event given that there is no such WM msg?

Actually there are only:
    Create = Interop.WM_CREATE,
    NonClientCreate = Interop.WM_NCCREATE,

Why is the WM_NCCREATE called non-client? Which precedes which? Is there any other WM event preceding these events which could be used?

Also id like for my OnLoad event to be entirely independent of wherever the Window will ever be visible or shown, it should work anyways.

## Event handlers

What kind of event handlers you plain to implement?
Will there be some kind of unified Event Bus?

I am currently building one such. And I quite wonder why class EnterIdleHandler does not actually implements an interface, is that on purpose or just not implemented yet?

## Embedding/Absorbing windows

Currently I am using this to create GUI for C# application interfacing a C++ program, and id love to embed the Window of C++ application within my C# application, what is the proper/meaningful/useful procedure to do this?

Currently i am doing some junk like this:

1. Set the C# app as parent of the C++ app
2. Set windowLong for styles on child to remove the borders and other junk
3. Calculate size/position within the C# app
4. Set childs size/position to fit within parent
5. Register size/position event handler for parent to update the child to right size/pos after parents move/rezise.

Or are you supposed to use some kind of Containers for this? Like you do with the embedding of ActiveX component?

**Comment by JeremyKuhne** [comment]
@Bia10 Sorry I didn't see this sooner. Feel free to tag me to get my attention in the future.

> WinForms have useful event OnLoad, how do I "replicate" this event given that there is no such WM msg?

In WinForms `OnLoad` is called after the handle is created. The thirty-two `Window` classes the handle is created when you construct the class so you don't really need it to start doing things to the `Window`.

WindowPositionChanged and Paint are the ones you're probably most interested in when they come through the first time. After WindowPositionChanged you'll have the correct window size. If you look at what comes through in the `Window.WindowProcedure` you'll see something like this:

```
GetFont
SetFont
ShowWindow
WindowPositionChanging
ActivateApp
NonClientActivate
GetIcon
Activate
...
SetFocus
NonClientPaint
EraseBackground
WindowPositionChanged
Size
Move
Paint
...
```

> What kind of event handlers you plain to implement?

I presume I'll add things like a paint handler, key handler, etc. as I continue implementing things. I was experimenting with this pay-for-play event handler model to keep things relatively light. In WinForms Controls are very heavy weight and quite slow as they have to always call all of the virtuals even when often they aren't being listened to.

I didn't add an interface to `EnterIdleHandler` as I didn't really need it. I don't really need one for the `MouseHandler` and will likely remove it.

You could follow the same pattern to create your own `OnLoadHandler` that listens for whatever it wants to and unhooks itself once it has what it needs.


> id love to embed the Window of C++ application within my C# application

If you're trying to embed the window from another process that can be incredibly difficult. You can just parent the window, but there are all sorts of caveats:

https://devblogs.microsoft.com/oldnewthing/20130412-00/?p=468

Parenting the window via `SetParent` should cause it to maintain its position with the parent window automatically.

The ActiveXControl host is specifically for ActiveX controls, I don't know that there is much you can leverage there unless you have an ActiveX control to host. I was trying to implement something akin to the WinForms AxHost from scratch so I could get a better handle on the bare minimum needed to host an ActiveX Control and understand what was necessary to do it all without COM interop.
