### ISSUE TITLE
DevCaps1

### ISSUE THREAD

**Issue by willibrandon** [JeremyKuhne/thirtytwo#3]
Hello @JeremyKuhne,

I was doing some holiday hacking and just wanted to share with you a program from Petzold's book that I implemented using your thirtytwo project.

https://github.com/willibrandon/thirtytwo/blob/device-caps/src/samples/DevCaps/Program.cs

Any thoughts are appreciated, and thank you for putting this together!

**Comment by willibrandon** [comment]
And the clover!

![Clover](https://github.com/JeremyKuhne/thirtytwo/assets/5017479/b3110bca-c144-49fc-8593-6e6ab75ebf42)

**Comment by JeremyKuhne** [comment]
Sorry @willibrandon I missed the notification on this. Very nice!

In my other, older project I went through most of what was in Petzold's book: https://github.com/JeremyKuhne/WInterop/tree/main/src/Samples/Petzold/5th. I really should port them over! 😆

**Comment by JeremyKuhne** [comment]
@willibrandon I ported Clover over from WInterop. My goal with these projects was to see if I could create a lightweight "WinForms" like experience with Win32. Trying to find the happy balance between exposing the details and making Win32 look more C# like.

**Comment by willibrandon** [comment]
Yes I've found thirtytwo to be a good way for me to learn Win32 while using C#.

Here is an interesting Neural Circuits simulator I really want to try and port over to thirtytwo for fun when/if I get the chance.
https://github.com/SimbeyGit/simbey/tree/main/desktop/NeuralCircuits
